Dev-FE-1/team2-intranet-project-

src/css/reset.css

Github issue #6
여백 초기화
리스트 스타일에 나타나는 기본 불릿 포인트 삭제

Style: reset.css 수정 업데이트

---

package-lock.json
package.json

- Install Handlebars via npm
- Update package.json and package-lock.json

Chore: Add Handlebars templating engine

---

.eslintignore
.husky/pre-commit
.prettierignore
package-lock.json
package.json

- 관련 자료: [Complete guide to ESLint, Prettier, husky and lint-staged - DEV Community](https://dev.to/shashwatnautiyal/complete-guide-to-eslint-prettier-husky-and-lint-staged-fh9)
- lint-staged와 husky 설정완료.
- commit을 할 때 마다 자동으로 포맷팅이됨.

Chore: lint-staged 와 husky 설정 완료

---

src/pages/header/Header.js

헤더 로고 이미지를 찾을 수 없음
페이지 이동시 일어나는 경로에러 수정

chore: 헤더 로고이미지 경로 수정

---

server/index.js
src/pages/employeeListTable/EmployeeListTableRows.js
src/pages/header/Header.js
src/pages/mypage/Mypage.js
vite.config.js

- 테스트용 User 데이터 관련 API 생성함  /api/v2/users
- vite.config.js에 새 프록시 생성 이제는 /api/v2 루트도 8080 서버 포트로 일치시켜줌.
- Header.js 오타 수정
- MyPage.js 프라미스 에러 수정. 에러 원인은 fetch(url) 코드에서 url 위치가 더 이상 이 프로젝트 폴더 안에 존재하지 않기 때문에 에러가 발생했었음. /api/v2/user를 fetch하도록 바꿈
- cors 옵션을 삭제함.

Fix/mypage promise error. MyPage.js 에러 수정

---

package-lock.json
package.json
server/index.js

Fix: 서버 라우팅 에러 해결, historyApiFallback 설정 추가

---

src/pages/header/Header.js
src/pages/index.js

Header.js는 페이지 테이스 용으로 수정했음(머지할 필요 없음)
Index.js에서 click addEventListener에서,
const route = {title, render}는 테스트 용으로 수정함(머지할 필요 없음) Github issue #12

fix: Header.js, index.js 필요없는 테스트 코드 삭제

---

src/pages/Home/HomeUpper.js
src/pages/index.js

- index.js의 라우터 함수를 변경했습니다.
- HomeUpper.js를 default export에서 export로 변경했습니다.

Refactor: index.js의 라우터 함수 변경

---

src/pages/index.js

- src/pages/index.js 의 라우트 함수 부분을 리펙토링함.

Refactor router function and routes object

---

src/pages/attendanceList/AttendanceList.css

design: AttendanceList 반응형 디자인 수정

---

src/pages/gallery/EmployeeGallery.js
src/pages/gallery/gallery.css

- EmployeeGallery.js 코드 안의 메서드들 추가함.
- gallery.css 코드 변경
-

Fix: gallery 부분에 이미지가 안 나오는 것을 고침, gallery.css도 변경

---

src/pages/gallery/AdminGallery.js

Fix: 기업 갤러리 컴포넌트도 수정함

---

src/pages/header/gnb.js

- 구글 폰트 문서를 보고 해결함
- https://www.inflearn.com/blogs/1039

Fix: 바닥 푸터 부분의 아이콘 이미지들이 나오지 않는 문제를 해결함.

---

src/pages/gallery/AdminGallery.js
src/pages/gallery/EmployeeGallery.js

- Fix: AdminGallery.js의 getGalleryData 함수 리턴 값을 변경함
- EmployeeGallery.js 도 동일하게 변경함.
```
async getGalleryData() {
try {
const response = await axios.get(this.galleryDataPath);
return response.data.data;
} catch (e) {
console.error('gallery.json 파일을 불러오는 데 실패했습니다.', e);
return [];
}
}
```

Fix: AdminGallery.js의 getGalleryData 함수 리턴 값을 변경함

---

src/pages/index.js

src/pages/index.js에 route()호출을 한 번으로 줄임.
Github issue #91

Fix: 클래스 두 번 초기화 에러 해결.

---

README.md
design/데이터베이스구조도_쿼리문.md

- README 문서에 배포 미러 사이트를 기재함.
- 쿼리문과 ERD를 design/데이터베이스구조도_쿼리문.md 에 넣어둠

Chore: 리드미 파일 업데이트, 쿼리문 파일 업데이트

---

src/pages/gallery/AdminGallery.js
src/pages/gallery/EmployeeGallery.js

- src/pages/gallery/AdminGallery.js,  src/pages/gallery/EmployeeGallery.js 를 수정

Fix: route-view에 gallery 클래스명이 추가되지 않도록 수정함.

---

package-lock.json
package.json
server/index.js

- 서버의 정적 파일 제공 시 content-type을 설정해주지 않아 발생한 문제임.
- css 파일도 content-type이 text/html로 나오던 버그를 해결함.

Fix: 서버의 정적 파일 제공에 content-type 설정 추가

---

src/components/modal/modal.js
src/pages/employeeListTable/EmployeeListTable.js
src/pages/employeeListTable/EmployeeListTableRows.js
src/pages/userinfo/UserInfo.js

- 직원 리스트 페이지에 삭제 버튼을 클릭했을 때 '삭제 하시겠습니까?' 경고용 모달창이 뜨게함.
- 모달창이 완전히 삭제가 안되고 테이블 아래에 모달창이 하나 생김.

Feat: 직원 리스트 페이지에 모달창을 추가함.

---

src/pages/employeeListTable/EmployeeListTable.js
src/pages/employeeListTable/EmployeeListTableRows.js

- 직원 리스트 페이지 EmployeeListTable.js 에  onClickTableRow 함수를 수정.
-  this.container에 클릭 이벤트 함수를 제거하고, 테이블로우에 클릭 이벤트 함수를 추가함

Fix: 직원 리스트 페이지에서 직원 클릭시 페이지 이동이 두 번되는 버그 해결

---

src/pages/LeaveApplicationList/LeaveApplicationForm.js
src/pages/LeaveApplicationList/LeaveApplicationItem.js

design: 기본 프로필 이미지 경로 수정 및 마크업 삽입

---

src/pages/LeaveApplicationList/LeaveApplicationItem.js
src/pages/LeaveApplicationList/LeaveApplicationList.js

Fix: Fix LeaveApplicationItem.js,

---

package-lock.json
package.json
src/pages/LeaveApplicationList/LeaveApplicationList.js

- npm i awilix connect-history-api-fallback cors date-and-time express lodash morgan nodemon sqlite sqlite3
-    `onClickEditButton` 함수에  `  if (!e.target.classList.contains('btn-edit')) return;` 를 추가함.

fix 근태 신청 페이지 삭제 버튼 누를시 모달창 생성 버그 해결

---

server/BaseRepository/DatabaseConnection.js
server/data/galleryDummyDatas.js
server/gallery/GalleryRepository.js
server/gallery/GalleryService.js
src/pages/gallery/AdminGallery.js
src/pages/gallery/EmployeeGallery.js

갤러리 화면이 아예 나오지 않던 에러 문제 해결
클라이언트가 아닌 서버쪽 문제임.

Fix: 갤러리 fetch 이미지 요청 에러

---

src/pages/mypage/Mypage.css
src/pages/mypage/Mypage.js
src/pages/userinfo/UserInfo.js

- 마이페이지에서 세션 정보를 받아오도록 구현
- 마이페이지에서 정보변경시 유저정보 페이지에서 세션 정보를 받아오도록 구현
- 유저정보 페이지에서 정보변경시 세션 정보 수정하도록 구현

Feat: 마이페이지, 유저정보 페이지 데이터 상태 관리 추가

---

src/pages/header/Header.js
src/pages/index.js

Hotfix/fix: 로그아웃 버튼 클릭 세선 비우기 및 로그아웃 처리 완료

---

server/inMemoDatabase.js
src/pages/index.js
src/pages/login/userLogin.js

Feature/lfrom the e/routing cp

---

src/assets/style/style.css
src/pages/Home/Home.css
src/pages/LeaveApplicationList/LeaveApplicationForm.css
src/pages/LeaveApplicationList/LeaveApplicationItem.css
src/pages/LeaveApplicationList/LeaveApplicationList.css
src/pages/attendancePreview/AttendanceList.css
src/pages/footer/Footer.css
src/pages/gallery/gallery.css
src/pages/header/Header.css
src/pages/login/login.css

전체 레이아웃은 가운데 정렬 => 모니터 가로사이즈가 너무 늘어나는 것 대비 변경됨

design: 반응형 디자인 수정 및 모니터가로 1024px을 최대로 세팅

---

server/attendance/AttendanceEntityKeyConverter.js
server/attendance/AttendanceRepository.js

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/workspace/server/utils/entityKeyConverter.js'
imported from /workspace/server/attendance/AttendanceRepository.js

Feat: 운영환경 모듈 import 에러 문제 발생 해결중

---

src/components/profileImage/ProfileImage.js
src/pages/Home/Home.js
src/pages/LeaveApplicationList/LeaveApplicationForm.css
src/pages/LeaveApplicationList/LeaveApplicationForm.js
src/pages/LeaveApplicationList/LeaveApplicationItem.js
src/pages/LeaveApplicationList/LeaveApplicationList.css
src/pages/footer/Footer.js
src/pages/login/login.css

fix: imgur 사용하여 이미지경로 수정

---

src/components/loading/Loading.css
src/components/loading/Loading.js

init: 로딩 페이지 컴포넌트 생성

---

server/users/userController.js
server/users/userRepository.js
server/users/userService.js
src/pages/employeeListTable/EmployeeListFetch.js
src/pages/employeeListTable/EmployeeListTable.js
src/pages/userinfo/UserInfo.js
src/pages/userinfo/Validator.js

Feat: 직원 등록 기능 업데이트

---

src/pages/Setting/Setting.js
src/pages/Setting/setting.css
src/pages/header/gnb.js
src/pages/index.js

Feat: 세팅 페이지에 로그아웃 버튼 추가

---

server/inMemoDatabase.js
server/index.js
server/initalizeData.js
src/pages/Home/Home.css
src/pages/Home/Home.js
src/pages/index.js
src/pages/login/userLogin.js

Feature/lfrom the e/login logic

---

server/users/userRepository.js
src/pages/employeeListTable/EmployeeListTableRows.js
src/pages/userinfo/UserInfo.js

아이디 중복이 이후에도 등록이나 수정이 안되는 문제가 있었으나 해결함

Feat: 아이디 중복성 체크 기능 버그 해결

---

server/BaseRepository/BaseRepository.js
server/users/userController.js
server/users/userRepository.js
server/users/userService.js
src/pages/employeeListTable/EmployeeListFetch.js
src/pages/employeeListTable/EmployeeListTable.js
src/pages/userinfo/UserInfo.js

- Feat: 직원 삭제 기능, 체크 박스 클릭한 직원들만 삭제함
- 여러명을 한 번에 삭제 가능함.
- 직원 아이디 값이 아닌 인덱스 값을 이용해서 삭제를 함.
- 백엔드에서는 직원 아이디 값을 이용해서 삭제하는데 반해, 프론트에서는 해당 직원의 인덱스 값만 전송함.

Feat: 직원 삭제 기능, 체크 박스 클릭한 직원들만 삭제함

---

server/index.js
server/users/userController.js
src/pages/userinfo/UserInfo.css
src/pages/userinfo/UserInfo.js
src/pages/userinfo/Validator.js

- 관리자 홈 화면에서 직원 상세 페이지에서 관리자홈으로 바로 이동할 수 있는 버튼 추가.
- 폼 제출시 딜레이 되도록함.

Feat: 유저 동선 개선, 딜레이 이미지 추가함.

---

server/index.js
server/users/userController.js
src/pages/userinfo/UserInfo.js
src/pages/userinfo/UserInfoModeChanger.js

Fix: server/user/userController.js에서 getAll 함수가 데이터를 두번 전송하지 않도록 수정함.

Refactor: userinfo.js 리펙토링중.

---

server/index.js

Fix: server/index.js 코드를 수정함. koyeb 빌드 실패 원인 분석중

Fix: server/index.js 코드를 수정함. koyeb 빌드 실패 원인 분석중

---

src/pages/userinfo/UserInfo.css
src/pages/userinfo/UserInfo.js
src/pages/userinfo/Validator.js

Fix: 관리자의 직원 등록, 수정 페이지에서만 ID 유효성 검사가 작동하게함

Fix: 관리자의 직원 등록, 수정 페이지에서만 ID 유효성 검사가 작동하게함

---

server/BaseRepository/DatabaseConnection.js

Fix: 데이터베이스를 메모리 데이터베이스로 롤백

---

src/components/profileImage/ProfileImage.js
src/components/profileImage/cloudinaryUploader.js
src/components/profileImage/eventHandlers.js
src/components/profileImage/imageUtils.js
src/components/profileImage/profileImageUtils.js
src/pages/index.js
src/pages/userinfo/UserInfo.js
src/pages/userinfo/constants.js
src/pages/userinfo/dataLoaders.js
src/pages/userinfo/dataManagement.js
src/pages/userinfo/eventHandlers.js
src/pages/userinfo/uiHelpers.js
src/pages/userinfo/validatorHelpers.js

경로: /src/components/profileImage
> 이미지 처리 함수 (imageUtils.js)
> Cloudinary 업로드 관련 함수 (cloudinaryUploader.js)
> 이벤트 핸들러만 모아 둔 함수 (eventHandlers.js)
> 이미지를 가져와서 업데이트 하는 함수 (profileImageUtils.js)
> 이미지 프로파일 클래스 (ProfileImage.js)
> #208 
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Dev/profile-image  프로필이미지 컴포넌트 함수분리

---

server/initalizeData.js
src/pages/Home/Home.js
src/pages/login/ErrorController.js
src/pages/login/Initialization.js
src/pages/login/LoginValid.js
src/pages/login/Submit.js
src/pages/login/loginUtil.js
src/pages/login/userLogin.js

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
로그인 컴포넌트를 리팩토링 하였습니다.
기존의 파일을 , 기능별로 4개의 클래스로 나누었습니다.
> ex) #이슈번호, #이슈번호
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Feacture/lfrom the e/refactoring

---

src/pages/mypage/LoadUserData.js
src/pages/mypage/Mypage.js
src/pages/mypage/MypageEventHandler.js

> 
- LoadUserData
- MypageEventHandler 크게 두 클래스로 분리했는데 사실 분리된 클래스 내에서 메서드 역할이
여전히 좀 달라서 고민입니다.
>git push --set-upstream origin refactor/mypage
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Refactor: Mypage 클래스 분리

---

src/pages/userinfo/UserInfo.js
src/pages/userinfo/constants.js
src/pages/userinfo/dataLoaders.js
src/pages/userinfo/dataManagement.js
src/pages/userinfo/eventHandlers.js
src/pages/userinfo/uiHelpers.js
src/pages/userinfo/validatorHelpers.js

- constants (클래스내부 상수)
- dataLoaders (데이터 로딩)
- dataManagement (데이터 관리)
- eventHandlers (이벤트 핸들러)
- uiHelpers (UI 관련된 헬퍼 함수)
- validatorHelpers (유효성 검사와 관련된 함수 및 이벤트 핸들러)
- UserInfo 클래스 
> Github issue #213
- 에러: UserInfo에 연결된 ProfileImage.js에서 사진변경버튼 클릭시 발생
- 에러: TypeError: getFormInputData is not a function. (In 'getFormInputData()', 'getFormInputData' is an instance of HTMLElement)
- 에러 처리: UserInfo.js에서 getFormInputData 함수에 .bind(this) 해주었지만 여전히 에러
```
setEditModeOrShowMode() {
if (this.isEditOrRegisterPage()) {
setSaveButtonElemDisable();
// handleFocusOutEventForValidCheck와 checkIsFormAllInputsValid 호출 시 this 컨텍스트를 바인딩
handleFocusOutEventForValidCheck(
this.el,
this.getFormInputData.bind(this), // 'this' 컨텍스트 바인딩 추가
this.isAdminPage.bind(this), // 'this' 컨텍스트 바인딩 추가 …
```

refactor: UserInfo 클래스 컴포넌트 함수 분리
